---
- hosts: all
  tasks:

    - block:
        - dnf: name=httpd state=present
        - service:
            name: httpd
            state: started
            enabled: true
      when: ansible_os_family == 'RedHat'
      become: yes

    - block:
        - apt: name=apache2 state=present
        - service: name=apache2 state=started enable=true
      when: ansible_os_family == 'Debian'
      become: yes

