---
- name: Install Node.js (npm plus dependencies)
  dnf: name=npm state=present enablerepo=epel

- name: Install forever module (to run our Node.js app).
  npm: name={{ item }} global=yes state=present
  with_items: "{{ node_npm_modules }}"
